name: WordPress Coding Standards

on: [push, pull_request]

jobs:
  phpcs:
    name: Run PHPCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run WordPress Coding Standards
        uses: 10up/wpcs-action@v1.2.0
        with:
          path: '.'            # Change this if your code is in a subfolder
          standard: 'WordPress' # Can also use WordPress-Extra, WordPress-Docs etc.
