name: PHP Coding Standards Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coding-standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, xdebug
          coverage: none

      - name: Configure Composer Allow-Plugins
        run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Dependencies
        run: composer install --no-progress

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs
