name: PHP Coding Standards Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensures submodules are initialized and updated

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Specify PHP version

      # Step 3: Install dependencies using Composer
      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      # Step 4: Run WordPress Coding Standards check
      - name: Run PHPCS
        run: |
          ./vendor/bin/phpcs --standard=WordPress ././
